# Generated by Django 3.2.4 on 2021-06-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=60, unique=True)),
                ('Cedula', models.IntegerField()),
                ('Imagen_de_Perfil', models.ImageField(upload_to='')),
                ('Pais', models.CharField(max_length=45)),
                ('Entidad', models.CharField(choices=[('EPS', 'EPS'), ('IPS', 'IPS'), ('ARL', 'ARL')], max_length=45)),
                ('Contraseña', models.CharField(max_length=16)),
            ],
        ),
    ]
