# Generated by Django 3.2.4 on 2021-06-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_imagen_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Imagen_de_Perfil',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
